library(ggplot2)
library(dplyr)
batting <- read.csv('Batting.csv')
print('printing the head of the dataframe')
print(head(batting))
print('printing the structure of the dataframe')
str(batting)
print('checking the head of the At Bats column of the batting dataframe')
print(head(batting$AB))
print('calling the head of the doubles column')
print(head(batting$X2B))
print('calculating the batting Average which is equal to: H(hits)/AB(at base)')
batting$BA <- (batting$H)/(batting$AB)
print('checking the tail of the batting average column which we created just now')
print(tail(batting$BA,5))
print('calculating the ob-base percentage as new column to dataframe: ')
batting$OBP <- (batting$H + batting$BB + batting$HBP)/(batting$AB + batting$AB + batting$HBP + batting$SF)
print('calculating the number of singles and attaching the column to the dataframe')
batting$X1B <- batting$H - batting$X2B - batting$X3B - batting$HR
print('calculating the slugging rate and attaching as a new colum to the dataframe')
batting$SLG <- ((1*batting$X1B) + (2*batting$X2B) + (3*batting$X3B) + (4*batting$H))/(batting$AB)
print("lets check the structure of the dataframe to see new columns")
print(str(batting))
print("-------------------------------------------------------------------")
print("now lets merge the salary and batting data")
print("loading the salary data..")
sal <- read.csv('Salaries.csv')
print('In summary, we can notice the minimum year in the yearID column. It is 1871. Sal column has data from 1985')
print('so we need to batting data batting data above 1985')
batting <- subset(batting, yearID >= 1985)
print(summary(batting))
print('merging salary and batting datasets into new dataframe: Combo....')
combo <- merge(batting, sal, by=c('yearID', 'playerID'))
print('now lets check the summary of combo....')
print(summary(combo))
print('Using the subset() function to get a data frame called lost_players from the combo data frame consisting of those 3 player')
lost_players <- subset(combo, playerID %in% c('giambja01','damonjo01','saenzol01'))
print('checking the lost_players dataframe')
print(lost_players)
print('now grabbing the subset where yearID=2001')
lost_players <- subset(lost_players, yearID==2001)
print('now grabbing the colums that we want....')
lost_players <- lost_players[,c('playerID','H','X2B','X3B','HR','OBP','SLG','BA','AB')]
print('printing the head of the lost players')
print(head(lost_players))
print('Now finding the replaced players fallowing the conditions: ')
avail.players <- filter(combo, yearID==2001)
print('plotting using ggplot2')
players.plot <- ggplot(avail.players, aes(x=OBP,y=salary))+geom_point()
print(players.plot)
print('From graph, we choose that as a cutt off point. There are also a lot of players with OBP==0. Lets get rid of them too')
avail.players <- subset(avail.players, salary <8000000,OBP>0)
print('The total AB of the lost players is 1469 (about 1500), we should probably cut off our avail.players at 1500/3= 500 AB')
avail.players <- subset(avail.players, AB>=500)
print('sort by OBP')
possible <- head(arrange(avail.players,desc(OBP)),10)
print('lets grab the columns we need')
possible <- possible[,c('playerID','OBP','AB','salary')]
print('we can choose three players from the mentioned below dataset: ')
print(possible)
